//
//  ABConstants.h
//  AirBridge
//
//  Created by Donutt on 2016. 11. 24..
//  Copyright © 2016년 TehranSlippers. All rights reserved.
//

#import <Foundation/Foundation.h>

#define AB_INTEGRATION_KEY_APPBOY @"Appboy"

#define AB_ATTRIBUTION_KEY_SOURCE @"AB_ATTRIBUTION_KEY_SOURCE"
#define AB_ATTRIBUTION_KEY_CAMPAIGN @"AB_ATTRIBUTION_KEY_CAMPAIGN"
#define AB_ATTRIBUTION_KEY_ADGROUP @"AB_ATTRIBUTION_KEY_ADGROUP"
#define AB_ATTRIBUTION_KEY_ADCREATIVE @"AB_ATTRIBUTION_KEY_ADCREATIVE"
#define AB_ATTRIBUTION_KEY_MEDIUM @"AB_ATTRIBUTION_KEY_MEDIUM"
#define AB_ATTRIBUTION_KEY_ADCONTENT @"AB_ATTRIBUTION_KEY_ADCONTENT"
#define AB_ATTRIBUTION_KEY_SEARCHKEYWORD @"AB_ATTRIBUTION_KEY_SEARCHKEYWORD"
#define AB_ATTRIBUTION_KEY_FINISHED_FLAG @"AB_ATTRIBUTION_KEY_FINISHED"

#define ABNETWORKING_PATH_V2_HOST @"https://core.airbridge.io/"
#define ABNETWORKING_PATH_V2_DEV_HOST @"http://core.dev.airbridge.io/"
#define ABNETWORKING_PATH_V2_ROUTE @"api/v2/apps/%@/events/mobile-app/%@"
#define ABNETWORKING_PATH_LOG_ROUTE @"api/v2/apps/%@/logs/mobile-app"

#define ABNETWORKING_PATH_V2_ATTRIBUTION_RESULT_ROUTE @"api/v2/apps/%@/events/mobile-app/%@/attribution-result?device_uuid=%@"
#define ABNETWORKING_PATH_V2_BACKUP_PATH @"https://secondary.airbridge.io/sqs/airbridge-mobile-events"

#define ABNETWORKING_ETYPE_LAUNCH 101
#define ABNETWORKING_ETYPE_GOAL 102
#define ABNETWORKING_ETYPE_BACKGROUND 103
#define ABNETWORKING_ETYPE_INSTALL 104
#define ABNETWORKING_ETYPE_TRACEVIEW 105
#define ABNETWORKING_ETYPE_TRACEACTION 106
#define ABNETWORKING_ETYPE_FOREGROUND 107
#define ABNETWORKING_ETYPE_SIMPLE_LAUNCH 108
#define ABNETWORKING_ETYPE_SIMPLE_GOAL 109
#define ABNETWORKING_ETYPE_SEND_DEEPLINK 9162

#define ABNETWORKING_ETYPE_V2_NEW_SESSION_LAUNCH @"9160"
#define ABNETWORKING_ETYPE_V2_LAUNCH @"9167"

#define ABNETWORKING_ETYPE_V2_INSTALL @"9161"

#define ABNETWORKING_ETYPE_V2_NEW_SESSION_DEEPLINK_LAUNCH @"9162" //딥링크 전 항상 최초 실행 또는 포그라운드가 들어가서 세션을 이미 새로 만들기에 해당 이벤트는 간헐적으로만 발생( foreground와 이 이벤트 간격사이에 session이 만료되었을 경우)
#define ABNETWORKING_ETYPE_V2_DEEPLINK_LAUNCH @"9168"

#define ABNETWORKING_ETYPE_V2_DEFERRED_DEEPLINK_INSTALL @"9163"
#define ABNETWORKING_ETYPE_V2_PAGEVIEW @"9164"
#define ABNETWORKING_ETYPE_V2_BACKGROUND @"9269"

#define ABNETWORKING_ETYPE_V2_NEW_SESSION_FOREGROUND @"9166"
#define ABNETWORKING_ETYPE_V2_FOREGROUND @"9165"


#define ABNETWORKING_ETYPE_V2_GOAL @"9360"

#define ABNETWORKING_ETYPE_V2_EXACTIVESTATUS_ACTIVE @1
#define ABNETWORKING_ETYPE_V2_EXACTIVESTATUS_INACTIVE @2
#define ABNETWORKING_ETYPE_V2_EXACTIVESTATUS_OFF @3

#define kBlankStr @""

typedef NS_ENUM(NSUInteger, ABLogType) {
    ABLOG_TYPE_ALL = 1,
    
    ABLOG_TYPE_DEBUG = 2,
    ABLOG_TYPE_INFO = 4,
    ABLOG_TYPE_WARNING = 8,
    ABLOG_TYPE_CRITICAL = 16,
    
    ABLOG_TYPE_NOT_LOGED = 1024
};

@interface ABConstants : NSObject

@end
